export enum MessageTypes {
  DOWNLOADING = "DOWNLOADING",
  LOADING = "LOADING",
  RESULT = "RESULT",
  INFERENCE_DONE = "INFERENCE_DONE",
  RESULT_PARTIAL = "RESULT_PARTIAL",
  INFERENCE_REQUEST = "INFERENCE_REQUEST",
}
